import { SystemSetting } from './settings-list';

/**
 * Mock settings data by category
 */

export const GENERAL_SETTINGS: SystemSetting[] = [
  {
    id: '1',
    key: 'app_name',
    value: 'OpenBook',
    valueType: 'string',
    category: 'general',
    label: 'Nombre de la aplicacion',
    description: 'Nombre mostrado en la interfaz',
    isSensitive: false,
    isActive: true,
    order: 1,
    defaultValue: 'OpenBook',
  },
  {
    id: '2',
    key: 'timezone',
    value: 'America/Bogota',
    valueType: 'string',
    category: 'general',
    label: 'Zona horaria',
    description: 'Zona horaria del sistema',
    isSensitive: false,
    isActive: true,
    order: 2,
    defaultValue: 'America/Bogota',
  },
  {
    id: '3',
    key: 'currency_code',
    value: 'COP',
    valueType: 'string',
    category: 'general',
    label: 'Codigo de moneda',
    description: 'Codigo ISO de la moneda (ej: COP, USD)',
    isSensitive: false,
    isActive: true,
    order: 3,
    defaultValue: 'COP',
  },
  {
    id: '4',
    key: 'date_format',
    value: 'DD/MM/YYYY',
    valueType: 'string',
    category: 'general',
    label: 'Formato de fecha',
    description: 'Formato para mostrar fechas',
    isSensitive: false,
    isActive: true,
    order: 4,
    defaultValue: 'DD/MM/YYYY',
  },
];

export const VARIABLES_SETTINGS: SystemSetting[] = [
  {
    id: '5',
    key: 'api_base_url',
    value: 'https://api.openbook.com',
    valueType: 'string',
    category: 'variables',
    label: 'URL base de la API',
    description: 'URL base para las peticiones a la API',
    isSensitive: false,
    isActive: true,
    order: 1,
    defaultValue: 'https://api.openbook.com',
  },
  {
    id: '6',
    key: 'environment',
    value: 'production',
    valueType: 'string',
    category: 'variables',
    label: 'Entorno',
    description: 'Entorno de ejecución del sistema',
    isSensitive: false,
    isActive: true,
    order: 2,
    defaultValue: 'production',
  },
  {
    id: '7',
    key: 'debug_mode',
    value: 'false',
    valueType: 'boolean',
    category: 'variables',
    label: 'Modo debug',
    description: 'Habilitar logs detallados para desarrollo',
    isSensitive: false,
    isActive: true,
    order: 3,
    defaultValue: 'false',
  },
  {
    id: '8',
    key: 'maintenance_mode',
    value: 'false',
    valueType: 'boolean',
    category: 'variables',
    label: 'Modo mantenimiento',
    description: 'Activar página de mantenimiento para usuarios',
    isSensitive: false,
    isActive: true,
    order: 4,
    defaultValue: 'false',
  },
];

export const SECURITY_SETTINGS: SystemSetting[] = [
  {
    id: '12',
    key: 'session_timeout_minutes',
    value: '60',
    valueType: 'number',
    category: 'security',
    label: 'Timeout de sesion (minutos)',
    description: 'Tiempo de inactividad antes de cerrar sesion',
    isSensitive: false,
    isActive: true,
    order: 1,
    validation: { min: 5, max: 1440 },
    defaultValue: '60',
  },
  {
    id: '13',
    key: 'max_login_attempts',
    value: '5',
    valueType: 'number',
    category: 'security',
    label: 'Intentos maximos de login',
    description: 'Intentos fallidos antes de bloquear cuenta',
    isSensitive: false,
    isActive: true,
    order: 2,
    validation: { min: 3, max: 10 },
    defaultValue: '5',
  },
  {
    id: '14',
    key: 'password_min_length',
    value: '8',
    valueType: 'number',
    category: 'security',
    label: 'Longitud minima de contrasena',
    description: 'Caracteres minimos para contrasenas',
    isSensitive: false,
    isActive: true,
    order: 3,
    validation: { min: 6, max: 32 },
    defaultValue: '8',
  },
];

export const AUDIT_SETTINGS: SystemSetting[] = [
  {
    id: '15',
    key: 'audit_retention_days',
    value: '365',
    valueType: 'number',
    category: 'audit',
    label: 'Dias de retencion de auditoria',
    description: 'Dias que se conservan los logs de auditoria',
    isSensitive: false,
    isActive: true,
    order: 1,
    validation: { min: 30, max: 3650 },
    defaultValue: '365',
  },
];

export const LIMITS_SETTINGS: SystemSetting[] = [
  {
    id: '16',
    key: 'max_file_size_mb',
    value: '10',
    valueType: 'number',
    category: 'limits',
    label: 'Tamano maximo de archivo (MB)',
    description: 'Tamano maximo permitido para archivos adjuntos',
    isSensitive: false,
    isActive: true,
    order: 1,
    validation: { min: 1, max: 100 },
    defaultValue: '10',
  },
  {
    id: '17',
    key: 'max_properties_per_condominium',
    value: '500',
    valueType: 'number',
    category: 'limits',
    label: 'Propiedades maximas por condominio',
    description: 'Limite de propiedades que puede tener un condominio',
    isSensitive: false,
    isActive: true,
    order: 2,
    validation: { min: 1, max: 10000 },
    defaultValue: '500',
  },
];
